# Generated by Django 4.1 on 2022-08-26 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0002_remove_post_like_or_dislike_count_likes_liker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(related_name='Subscribed_Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
