# Generated by Django 4.1 on 2022-08-27 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0004_alter_post_post_pic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('post_id', 'liker_id')},
        ),
    ]
