# Generated by Django 4.1 on 2022-08-30 17:16

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bodytext',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1000, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
