# Generated by Django 4.1 on 2022-08-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('createdAt',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('createdAt',)},
        ),
    ]
