# Generated by Django 4.1 on 2022-08-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-createdAt',)},
        ),
    ]
